### ISSUE TITLE
Add weights to compute metrics

### ISSUE THREAD

**Issue by deepcharles** [ramp-kits/human_locomotion#14]
Has anyone already tried to add weights to certain instances computing the score? Something like the `sample_weight` option in [scikit-learn f1-score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html).

I would like to penalize more the errors on the 'Neurological' and 'Orthopedic' groups.

**Comment by agramfort** [comment]
look https://github.com/ramp-kits/fake_news/blob/master/problem.py#L18 for
inspiration

>

**Comment by agramfort** [comment]
actually it's different. Not sure if it's possible in ramp at this point.

**Comment by deepcharles** [comment]
Noted. It is not necessary (just nice to have).
