### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by lucyleeow** [ramp-kits/human_locomotion#8]
Very interesting challenge. I just have some questions/suggestions:

`human_locomotion_starting_kit.ipynb`

* Can you provide the number of subjects in each group and subgroup (e.g. health,  Parkinson's disease)
* Since you detail this:

> All signals have been acquired at 100 Hz with two brands of IMUs: XSens&trade; and Technoconcept&reg;.
Both were attached to the dorsal face of each foot.

Maybe you can mention if the signal from the 2 IMUs were averaged/how they were treated. Or remove it altogether if this detail is not relevant.

* It's not clear that the number of steps (i.e. `len(step_list)`) and the data points acquired (i.e., `len(trial)`) is different for each trial. It would be nice to make this explicit.
* Can you clarify this?

> Some of the described variables can take the value "NC" which stands for "Not Communicated". This label replaces missing data and depending on the variable may affect up to 2% of the database.

I couldn't find any 'NC' values in the training data `trail`?

* Maybe you could re-word this so you don't have to repeat yourself?

>  Precision (or positive predictive value). A detected step is counted as correct if the mean of its start and end times lies inside an annotated step. An annotated step can only be detected one time. If several detected steps correspond to the same annotated step, all but one are considered as false. The precision is the number of correctly detected steps divided by the total number of detected steps.
Recall (or sensitivity). An annotated step is counted as detected if the mean of its start and end times lies inside a detected step. A detected step can only be used to detect one annotated step. If several annotated steps are detected with the same detected step, all but one are considered undetected. The recall is the number of detected annotated steps divided by the total number of annotated steps.

* Could you also give an example of a detected step that is counted and one where several detected steps correspond to the same annotated step (just to help people understand/clarify)?
* It's not clear whether you can use the metadata for prediction? And if it isn't, is there a way to prevent/check if students are using it?

`problem.py`
* where is `pairwise` and `is_iterable` used?

**Comment by lucyleeow** [comment]
Also is seaborn required in:
https://github.com/ramp-kits/human-locomotion/blob/67c893e19af761305379b64f3f9799b51caf7538/.travis.yml#L13

(cc @agramfort )

**Comment by deepcharles** [comment]
I'll do it today or tomorrow.

Also, just so you know, I will slightly change the computation of the f-score to put more weight on instances from the "Orthopedic" and "Neurological" groups (since they are more complex than the "Healthy" group and more clinically important).

**Comment by lucyleeow** [comment]
> Also, just so you know, I will slightly change the computation of the f-score to put more weight on instances from the "Orthopedic" and "Neurological" groups (since they are more complex than the "Healthy" group and more clinically important).

That's a good idea! It might be worthwhile mentioning this in the challenge just so participants know.

**Comment by deepcharles** [comment]
Yes, I will change the notebook accordingly.

**Comment by deepcharles** [comment]
In #13, I have integrated your suggestions

The details:

>     * Can you provide the number of subjects in each group and subgroup (e.g. health,  Parkinson's disease)

I have added the proportion of each group (in the {training, testing, private} data set) and the exact number of instances from each group in the section "Simple data exploration".

>     * Since you detail this:
> 
> 
> > All signals have been acquired at 100 Hz with two brands of IMUs: XSens™ and Technoconcept®.
> > Both were attached to the dorsal face of each foot.
> 
> Maybe you can mention if the signal from the 2 IMUs were averaged/how they were treated. Or remove it altogether if this detail is not relevant.

The exact treatment of the signals is not really relevant to the challenge. However the sensors can output slightly different signals so I would like to leave this information so that participants can use it (or not). For instance, they could learn a model for XSens and another for TCon (the two sensor brands).

>     * It's not clear that the number of steps (i.e. `len(step_list)`) and the data points acquired (i.e., `len(trial)`) is different for each trial. It would be nice to make this explicit.
> 
>     * Can you clarify this?

I have added several sentences to clarify this. 

> > Some of the described variables can take the value "NC" which stands for "Not Communicated". This label replaces missing data and depending on the variable may affect up to 2% of the database.
> 
> I couldn't find any 'NC' values in the training data `trail`?

I have added the following sentence in the notebook: 'Some metadata (namely .age, .height, .weight, .bmi and .laterality) can take the value "NC" which stands for "Not Communicated".'

>     * Maybe you could re-word this so you don't have to repeat yourself?
> 
> 
> > Precision (or positive predictive value). A detected step is counted as correct if the mean of its start and end times lies inside an annotated step. An annotated step can only be detected one time. If several detected steps correspond to the same annotated step, all but one are considered as false. The precision is the number of correctly detected steps divided by the total number of detected steps.
> > Recall (or sensitivity). An annotated step is counted as detected if the mean of its start and end times lies inside a detected step. A detected step can only be used to detect one annotated step. If several annotated steps are detected with the same detected step, all but one are considered undetected. The recall is the number of detected annotated steps divided by the total number of annotated steps.

Done (I did the best I could).

>     * Could you also give an example of a detected step that is counted and one where several detected steps correspond to the same annotated step (just to help people understand/clarify)?

Added two examples.

>     * It's not clear whether you can use the metadata for prediction? And if it isn't, is there a way to prevent/check if students are using it?

Added the following sentence: 'Metadata are provided to help with the step detection task. For instance, one could learn a different model for each pathology group. But it is not compulsory to use them.' 

> `problem.py`
> 
>     * where is `pairwise` and `is_iterable` used?

I removed unused code.

Many thanks for the suggestions, the notebook is now a lot clearer.

**Comment by deepcharles** [comment]
closing. Feel free to reopen.

**Comment by lucyleeow** [comment]
No problems, thanks for being so quick.

> The exact treatment of the signals is not really relevant to the challenge. However the sensors can output slightly different signals so I would like to leave this information so that participants can use it (or not). For instance, they could learn a model for XSens and another for TCon (the two sensor brands

I think I misunderstood then. Are the 2 sensors measuring the same thing? Are signals from both sensors are included in one trial? Or is there 2 different trials, one for the signals from each sensor?

**Comment by deepcharles** [comment]
When a subject does a trial, he wears both sensors at the same time. Then step detection is applied on the data sent by the left sensor (8D signal) to recover the left footsteps and on the data sent by the right sensor (another 8D signal) to recover the right footsteps.

In practice, both sensors are synchronized and they send a 16D signal.
I splitted in two this 16D signals because
1) we treated both sensors seperately when we worked on step detection so I found it natural
2) if I merge the two sensors, I also have to merge the two labels (basically an array of shape (n_step_left, 2) and another of shape (n_step_right, 2)).

For 1), I see now that what was natural for me may not be the best way, so I am open to suggestions.
For 2), if you think that it will not be too strange for students to predict a list of two arrays with different lengths, I can change the data format and merge the two sensors.

In any case, for now, I will rephrase a bit the notebook so that it is clearer, and if any of you think of a better way, I will integrate it.

**Comment by lucyleeow** [comment]
Ohh I see, so the sensors on the left and right foot are different? That's an interesting aspect of the challenge!

**Comment by deepcharles** [comment]
I have modified a bit the notebook (#16). Thanks again for all your suggestions.

To me it looks ok now. @lucyleeow @agramfort

**Comment by lucyleeow** [comment]
Maybe some some minor amendments to this paragraph, changes bolded:

First, **a** IMU (Inertial Measurement Unit) that recorded accelerations and angular velocities, was attached to **each foot**. All signals have been acquired at 100 Hz with two brands of IMUs: XSens™ and Technoconcept®. **One brand of** IMU was attached to the dorsal face of **each foot**. 

Was the branch attached to the left foot of all participants the same? This may be relevant if there are 'differences' between sensor brands. You can state which was used for which foot if so.

**Comment by agramfort** [comment]
ok so next move is to try to deploy this RAMP on website?

>

**Comment by deepcharles** [comment]
> Maybe some some minor amendments to this paragraph, changes bolded:
> 
> First, **a** IMU (Inertial Measurement Unit) that recorded accelerations and angular velocities, was attached to **each foot**. All signals have been acquired at 100 Hz with two brands of IMUs: XSens™ and Technoconcept®. **One brand of** IMU was attached to the dorsal face of **each foot**.

I have added the changes (#18)

> Was the branch attached to the left foot of all participants the same? This may be relevant if there are 'differences' between sensor brands. You can state which was used for which foot if so.

Both feet had the same brand of sensor. Also added a sentence to clarify (#18)

**Comment by lucyleeow** [comment]
> Both feet had the same brand of sensor.

Thanks for clarifying. So each participant wore the same brand on both feet but the brand of IMU was different between different participants? (Sorry to keep asking!)

**Comment by deepcharles** [comment]
Yes exactly.

**Comment by lucyleeow** [comment]
> ok so next move is to try to deploy this RAMP on website?

@agramfort I think we still need a private ramp-data repo in https://github.com/ramp-data with least a `prepare_data.py`. To follow guillaume's guide, we should also put the data on OFS. I can give @deepcharles access rights to both if you're happy?

**Comment by lucyleeow** [comment]
Also we need private test data, and may need to re-split the data, depending on how much data you have.

**Comment by deepcharles** [comment]
I have already splitted the data set in a public set and a private set as described in [here](https://paris-saclay-cds.github.io/ramp-docs/ramp-workflow/stable/data.html).

The public set (train and test) is equal to the training private set.

I can send you the download link by mail.

**Comment by lucyleeow** [comment]
> I have already splitted the data set in a public set and a private set as described in [here](https://paris-saclay-cds.github.io/ramp-docs/ramp-workflow/stable/data.html).

That's great! Still would require a repo in https://github.com/ramp-data. I'll check how best to proceed with @agramfort
